package app_test

import (
	"bytes"
	"path/filepath"
	"strings"
	"testing"

	"sbl/internal/app"
	"sbl/internal/testutil"
)

func TestValidateFixtureViaApp(t *testing.T) {
	root := testutil.CopyFixture(t, "site-basic")
	if err := app.Validate(app.ValidateOptions{SiteRoot: root}); err != nil {
		t.Fatalf("Validate returned error: %v", err)
	}
}

func TestBuildBasicSite(t *testing.T) {
	root := testutil.CopyFixture(t, "site-basic")
	var stdout bytes.Buffer

	err := app.Build(app.BuildOptions{
		SiteRoot: root,
		Clean:    true,
		Stdout:   &stdout,
	})
	if err != nil {
		t.Fatalf("Build returned error: %v", err)
	}

	if !strings.Contains(stdout.String(), "built 1 posts and 1 pages") {
		t.Fatalf("unexpected build summary: %q", stdout.String())
	}

	indexHTML := testutil.ReadFile(t, filepath.Join(root, "public", "index.html"))
	postHTML := testutil.ReadFile(t, filepath.Join(root, "public", "posts", "hello-world", "index.html"))
	pageHTML := testutil.ReadFile(t, filepath.Join(root, "public", "pages", "about", "index.html"))
	archiveHTML := testutil.ReadFile(t, filepath.Join(root, "public", "archive", "index.html"))
	feedXML := testutil.ReadFile(t, filepath.Join(root, "public", "feed.xml"))
	sitemapXML := testutil.ReadFile(t, filepath.Join(root, "public", "sitemap.xml"))
	robotsTXT := testutil.ReadFile(t, filepath.Join(root, "public", "robots.txt"))
	swsConfig := testutil.ReadFile(t, filepath.Join(root, "deploy", "sws.toml"))

	if !strings.Contains(indexHTML, `href="/assets/site.`) {
		t.Fatalf("index page missing hashed stylesheet: %s", indexHTML)
	}
	if !strings.Contains(indexHTML, "Hello World") || !strings.Contains(archiveHTML, "Hello World") {
		t.Fatalf("list pages missing post content")
	}
	if !strings.Contains(postHTML, "This is the first post generated by") {
		t.Fatalf("post page missing rendered body: %s", postHTML)
	}
	if !strings.Contains(pageHTML, "Why this page exists") || !strings.Contains(pageHTML, "/posts/hello-world/") {
		t.Fatalf("page output missing expected content: %s", pageHTML)
	}
	if !strings.Contains(feedXML, "<rss") || !strings.Contains(feedXML, "Hello World") {
		t.Fatalf("feed missing expected content: %s", feedXML)
	}
	if !strings.Contains(sitemapXML, "/posts/hello-world/") {
		t.Fatalf("sitemap missing post URL: %s", sitemapXML)
	}
	if !strings.Contains(sitemapXML, "/pages/about/") {
		t.Fatalf("sitemap missing page URL: %s", sitemapXML)
	}
	if !strings.Contains(robotsTXT, "Sitemap: https://example.test/sitemap.xml") {
		t.Fatalf("robots.txt missing sitemap: %s", robotsTXT)
	}
	if !strings.Contains(swsConfig, `source = "/archive/index.html"`) {
		t.Fatalf("generated SWS config missing structural redirects: %s", swsConfig)
	}
	if !strings.Contains(swsConfig, `source = "/pages/{*}/index.html"`) {
		t.Fatalf("generated SWS config missing pages redirect: %s", swsConfig)
	}
}

func TestBuildRichSite(t *testing.T) {
	root := testutil.CopyFixture(t, "site-rich-content")

	err := app.Build(app.BuildOptions{
		SiteRoot: root,
		Clean:    true,
	})
	if err != nil {
		t.Fatalf("Build returned error: %v", err)
	}

	postHTML := testutil.ReadFile(t, filepath.Join(root, "public", "posts", "rich-content", "index.html"))
	swsConfig := testutil.ReadFile(t, filepath.Join(root, "deploy", "sws.toml"))

	if !strings.Contains(postHTML, `class="math math-inline"`) {
		t.Fatalf("post page missing inline math markup: %s", postHTML)
	}
	if !strings.Contains(postHTML, `class="math math-display"`) {
		t.Fatalf("post page missing display math markup: %s", postHTML)
	}
	if !strings.Contains(postHTML, `/assets/posts/rich-content/layout.`) {
		t.Fatalf("post page missing rewritten local asset URL: %s", postHTML)
	}
	if !strings.Contains(postHTML, `/assets/posts/rich-content/diagram-1.`) {
		t.Fatalf("post page missing Mermaid asset URL: %s", postHTML)
	}
	if !strings.Contains(postHTML, "chroma") {
		t.Fatalf("post page missing syntax highlighted code: %s", postHTML)
	}
	if !strings.Contains(swsConfig, `source = "/notes/old-rich-content/"`) {
		t.Fatalf("generated SWS config missing alias redirect: %s", swsConfig)
	}

	testutil.MustGlobOne(t, filepath.Join(root, "public", "assets", "posts", "rich-content", "layout.*.svg"))
	testutil.MustGlobOne(t, filepath.Join(root, "public", "assets", "posts", "rich-content", "diagram-1.*.svg"))
}
