package app_test

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"sbl/internal/app"
	"sbl/internal/testutil"
)

func TestValidateFixtureViaApp(t *testing.T) {
	root := testutil.CopyFixture(t, "site-basic")
	if err := app.Validate(app.ValidateOptions{SiteRoot: root}); err != nil {
		t.Fatalf("Validate returned error: %v", err)
	}
}

func TestValidateRejectsMissingSiteRoot(t *testing.T) {
	root := filepath.Join(t.TempDir(), "missing-site")

	err := app.Validate(app.ValidateOptions{SiteRoot: root})
	if err == nil || !strings.Contains(err.Error(), "site root does not exist") {
		t.Fatalf("expected missing site root error, got: %v", err)
	}
}

func TestBuildRejectsMissingSiteRoot(t *testing.T) {
	root := filepath.Join(t.TempDir(), "missing-site")

	err := app.Build(app.BuildOptions{
		SiteRoot: root,
		BaseURL:  "https://example.test",
	})
	if err == nil || !strings.Contains(err.Error(), "site root does not exist") {
		t.Fatalf("expected missing site root error, got: %v", err)
	}
}

func TestBuildDoesNotCleanOutputWhenValidationFails(t *testing.T) {
	root := t.TempDir()
	outputDir := filepath.Join(root, "dist")
	sentinelPath := filepath.Join(outputDir, "keep.txt")

	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		t.Fatalf("MkdirAll returned error: %v", err)
	}
	if err := os.WriteFile(sentinelPath, []byte("keep"), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	err := app.Build(app.BuildOptions{
		SiteRoot:  root,
		OutputDir: outputDir,
		BaseURL:   "https://example.test",
		Clean:     true,
	})
	if err == nil || !strings.Contains(err.Error(), "site config file is required") {
		t.Fatalf("expected missing config error, got: %v", err)
	}
	if _, err := os.Stat(sentinelPath); err != nil {
		t.Fatalf("expected output directory to remain untouched, stat returned: %v", err)
	}
}

func TestValidateRejectsMisplacedPostFile(t *testing.T) {
	root := t.TempDir()

	if err := os.MkdirAll(filepath.Join(root, "config"), 0o755); err != nil {
		t.Fatalf("MkdirAll returned error: %v", err)
	}
	if err := os.MkdirAll(filepath.Join(root, "content", "posts"), 0o755); err != nil {
		t.Fatalf("MkdirAll returned error: %v", err)
	}
	if err := os.WriteFile(filepath.Join(root, "config", "site.yaml"), []byte("title: Test\nbase_url: https://example.test\n"), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}
	if err := os.WriteFile(filepath.Join(root, "content", "posts", "wrong-layout.md"), []byte("---\ntitle: Wrong Layout\ndate: 2026-04-13\nsummary: Misplaced file.\n---\n"), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	err := app.Validate(app.ValidateOptions{SiteRoot: root})
	if err == nil || !strings.Contains(err.Error(), "unexpected file in posts directory") {
		t.Fatalf("expected misplaced post error, got: %v", err)
	}
}

func TestBuildBasicSite(t *testing.T) {
	root := testutil.CopyFixture(t, "site-basic")
	var stdout bytes.Buffer

	err := app.Build(app.BuildOptions{
		SiteRoot: root,
		Clean:    true,
		Stdout:   &stdout,
	})
	if err != nil {
		t.Fatalf("Build returned error: %v", err)
	}

	if !strings.Contains(stdout.String(), "built 1 posts and 1 pages") {
		t.Fatalf("unexpected build summary: %q", stdout.String())
	}

	indexHTML := testutil.ReadFile(t, filepath.Join(root, "public", "index.html"))
	postHTML := testutil.ReadFile(t, filepath.Join(root, "public", "posts", "hello-world", "index.html"))
	pageHTML := testutil.ReadFile(t, filepath.Join(root, "public", "pages", "about", "index.html"))
	archiveHTML := testutil.ReadFile(t, filepath.Join(root, "public", "archive", "index.html"))
	feedXML := testutil.ReadFile(t, filepath.Join(root, "public", "feed.xml"))
	sitemapXML := testutil.ReadFile(t, filepath.Join(root, "public", "sitemap.xml"))
	robotsTXT := testutil.ReadFile(t, filepath.Join(root, "public", "robots.txt"))
	swsConfig := testutil.ReadFile(t, filepath.Join(root, "deploy", "sws.toml"))

	if !strings.Contains(indexHTML, `href="/assets/site.`) {
		t.Fatalf("index page missing hashed stylesheet: %s", indexHTML)
	}
	if !strings.Contains(indexHTML, "Hello World") || !strings.Contains(archiveHTML, "Hello World") {
		t.Fatalf("list pages missing post content")
	}
	if !strings.Contains(postHTML, "This is the first post generated by") {
		t.Fatalf("post page missing rendered body: %s", postHTML)
	}
	for name, html := range map[string]string{
		"index":   indexHTML,
		"archive": archiveHTML,
		"post":    postHTML,
	} {
		if !strings.Contains(html, `<ul class="post-tags" aria-label="Tags">`) ||
			!strings.Contains(html, "<li>intro</li>") ||
			!strings.Contains(html, "<li>go</li>") {
			t.Fatalf("%s page missing post tags under the summary: %s", name, html)
		}
	}
	if !strings.Contains(pageHTML, "Why this page exists") || !strings.Contains(pageHTML, "/posts/hello-world/") {
		t.Fatalf("page output missing expected content: %s", pageHTML)
	}
	if !strings.Contains(feedXML, "<rss") || !strings.Contains(feedXML, "Hello World") {
		t.Fatalf("feed missing expected content: %s", feedXML)
	}
	if !strings.Contains(sitemapXML, "/posts/hello-world/") {
		t.Fatalf("sitemap missing post URL: %s", sitemapXML)
	}
	if !strings.Contains(sitemapXML, "/pages/about/") {
		t.Fatalf("sitemap missing page URL: %s", sitemapXML)
	}
	if !strings.Contains(robotsTXT, "Sitemap: https://example.test/sitemap.xml") {
		t.Fatalf("robots.txt missing sitemap: %s", robotsTXT)
	}
	if !strings.Contains(swsConfig, `source = "/archive/index.html"`) {
		t.Fatalf("generated SWS config missing structural redirects: %s", swsConfig)
	}
	if !strings.Contains(swsConfig, `source = "/pages/{*}/index.html"`) {
		t.Fatalf("generated SWS config missing pages redirect: %s", swsConfig)
	}
	if strings.Contains(postHTML, `data-sbl-render="1"`) {
		t.Fatalf("basic post unexpectedly bootstrapped client rendering: %s", postHTML)
	}
	if _, err := os.Stat(filepath.Join(root, "public", "assets", "vendor")); !os.IsNotExist(err) {
		t.Fatalf("expected no vendored browser assets for basic site, stat returned: %v", err)
	}
}

func TestBuildRichSite(t *testing.T) {
	root := testutil.CopyFixture(t, "site-rich-content")

	err := app.Build(app.BuildOptions{
		SiteRoot: root,
		Clean:    true,
	})
	if err != nil {
		t.Fatalf("Build returned error: %v", err)
	}

	postHTML := testutil.ReadFile(t, filepath.Join(root, "public", "posts", "rich-content", "index.html"))
	swsConfig := testutil.ReadFile(t, filepath.Join(root, "deploy", "sws.toml"))

	if !strings.Contains(postHTML, `class="sbl-math-inline"`) || !strings.Contains(postHTML, `class="sbl-math-display"`) {
		t.Fatalf("post page missing math placeholders: %s", postHTML)
	}
	if !strings.Contains(postHTML, `class="sbl-mermaid"`) {
		t.Fatalf("post page missing Mermaid placeholder: %s", postHTML)
	}
	if !strings.Contains(postHTML, `data-katex-js-url="/assets/vendor/katex-`) {
		t.Fatalf("post page missing client render bootstrap for KaTeX: %s", postHTML)
	}
	if !strings.Contains(postHTML, `data-mermaid-js-url="/assets/vendor/mermaid-`) {
		t.Fatalf("post page missing client render bootstrap for Mermaid: %s", postHTML)
	}
	if !strings.Contains(postHTML, `href="/assets/vendor/prism-`) {
		t.Fatalf("post page missing Prism stylesheet: %s", postHTML)
	}
	if !strings.Contains(postHTML, `data-prism-core-js-url="/assets/vendor/prism-`) {
		t.Fatalf("post page missing Prism core bootstrap URL: %s", postHTML)
	}
	if !strings.Contains(postHTML, `data-prism-autoloader-js-url="/assets/vendor/prism-`) {
		t.Fatalf("post page missing Prism autoloader bootstrap URL: %s", postHTML)
	}
	if !strings.Contains(postHTML, `data-prism-languages-path="/assets/vendor/prism-`) {
		t.Fatalf("post page missing Prism languages path: %s", postHTML)
	}
	if !strings.Contains(postHTML, `/assets/posts/rich-content/layout.`) {
		t.Fatalf("post page missing rewritten local asset URL: %s", postHTML)
	}
	if !strings.Contains(postHTML, `class="language-go"`) {
		t.Fatalf("post page missing client-highlightable code block: %s", postHTML)
	}
	if strings.Contains(postHTML, `class="chroma"`) {
		t.Fatalf("post page still contains server-side highlighting markup: %s", postHTML)
	}
	if strings.Contains(postHTML, `<span class="kn">`) {
		t.Fatalf("post page still contains server-side token markup: %s", postHTML)
	}
	if !strings.Contains(swsConfig, `source = "/notes/old-rich-content/"`) {
		t.Fatalf("generated SWS config missing alias redirect: %s", swsConfig)
	}

	testutil.MustGlobOne(t, filepath.Join(root, "public", "assets", "vendor", "prism-*", "themes", "prism.min.css"))
	testutil.MustGlobOne(t, filepath.Join(root, "public", "assets", "vendor", "prism-*", "components", "prism-core.min.js"))
	testutil.MustGlobOne(t, filepath.Join(root, "public", "assets", "vendor", "prism-*", "plugins", "autoloader", "prism-autoloader.min.js"))
	testutil.MustGlobOne(t, filepath.Join(root, "public", "assets", "vendor", "prism-*", "components", "prism-clike.min.js"))
	testutil.MustGlobOne(t, filepath.Join(root, "public", "assets", "vendor", "prism-*", "components", "prism-go.min.js"))
	if matches, err := filepath.Glob(filepath.Join(root, "public", "assets", "vendor", "prism-*", "components", "prism-python.min.js")); err != nil {
		t.Fatalf("glob returned error: %v", err)
	} else if len(matches) != 0 {
		t.Fatalf("unexpected unused Prism component copied: %v", matches)
	}
	testutil.MustGlobOne(t, filepath.Join(root, "public", "assets", "posts", "rich-content", "layout.*.svg"))
	if strings.Contains(postHTML, `/assets/posts/rich-content/diagram-1.`) {
		t.Fatalf("post page still references a pre-rendered Mermaid asset: %s", postHTML)
	}
}

func TestBuildRichSiteUsesConfiguredPrismTheme(t *testing.T) {
	root := testutil.CopyFixture(t, "site-rich-content")
	configPath := filepath.Join(root, "config", "site.yaml")
	config := testutil.ReadFile(t, configPath) + "prism_theme: okaidia\n"
	if err := os.WriteFile(configPath, []byte(config), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	err := app.Build(app.BuildOptions{
		SiteRoot: root,
		Clean:    true,
	})
	if err != nil {
		t.Fatalf("Build returned error: %v", err)
	}

	postHTML := testutil.ReadFile(t, filepath.Join(root, "public", "posts", "rich-content", "index.html"))
	if !strings.Contains(postHTML, `href="/assets/vendor/prism-1.30.0/themes/prism-okaidia.min.css"`) {
		t.Fatalf("post page missing configured Prism theme: %s", postHTML)
	}
	testutil.MustGlobOne(t, filepath.Join(root, "public", "assets", "vendor", "prism-*", "themes", "prism-okaidia.min.css"))
	if matches, err := filepath.Glob(filepath.Join(root, "public", "assets", "vendor", "prism-*", "themes", "prism.min.css")); err != nil {
		t.Fatalf("glob returned error: %v", err)
	} else if len(matches) != 0 {
		t.Fatalf("unexpected default Prism theme copied: %v", matches)
	}
}

func TestValidateRejectsUnknownPrismTheme(t *testing.T) {
	root := testutil.CopyFixture(t, "site-basic")
	configPath := filepath.Join(root, "config", "site.yaml")
	config := testutil.ReadFile(t, configPath) + "prism_theme: missing\n"
	if err := os.WriteFile(configPath, []byte(config), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	err := app.Validate(app.ValidateOptions{SiteRoot: root})
	if err == nil || !strings.Contains(err.Error(), `unknown prism_theme "missing"`) {
		t.Fatalf("expected unknown Prism theme error, got: %v", err)
	}
}

func TestBuildPrunesUnusedVendorAssetsOnRebuild(t *testing.T) {
	root := testutil.CopyFixture(t, "site-rich-content")

	err := app.Build(app.BuildOptions{
		SiteRoot: root,
		Clean:    true,
	})
	if err != nil {
		t.Fatalf("initial build returned error: %v", err)
	}

	markdown := `---
title: "Rich Content"
date: 2026-04-12
updated: 2026-04-12
summary: "No longer uses client-rendered browser assets."
draft: false
---

## Plain text

This rebuild should not emit KaTeX, Mermaid, or Prism assets.
`
	if err := os.WriteFile(filepath.Join(root, "content", "posts", "rich-content", "index.md"), []byte(markdown), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	err = app.Build(app.BuildOptions{
		SiteRoot: root,
	})
	if err != nil {
		t.Fatalf("rebuild returned error: %v", err)
	}

	if _, err := os.Stat(filepath.Join(root, "public", "assets", "vendor")); !os.IsNotExist(err) {
		t.Fatalf("expected vendored browser assets to be pruned on rebuild, stat returned: %v", err)
	}
}

func TestBuildPrintsTimings(t *testing.T) {
	root := testutil.CopyFixture(t, "site-basic")
	var stdout bytes.Buffer

	err := app.Build(app.BuildOptions{
		SiteRoot: root,
		Clean:    true,
		Stdout:   &stdout,
		Timings:  true,
	})
	if err != nil {
		t.Fatalf("Build returned error: %v", err)
	}

	output := stdout.String()
	for _, needle := range []string{
		"built 1 posts and 1 pages",
		"timings:",
		"  load_site_config: ",
		"  validate_layout: ",
		"  load_posts: ",
		"  load_pages: ",
		"  validate_content: ",
		"  load_templates: ",
		"  build_static_assets: ",
		"  build_vendor_assets: ",
		"  render_posts: ",
		"  render_pages: ",
		"  render_auxiliary: ",
		"  write_deploy_config: ",
		"  total: ",
	} {
		if !strings.Contains(output, needle) {
			t.Fatalf("build output missing %q in %q", needle, output)
		}
	}
}

func TestValidatePrintsTimings(t *testing.T) {
	root := testutil.CopyFixture(t, "site-basic")
	var stdout bytes.Buffer

	err := app.Validate(app.ValidateOptions{
		SiteRoot: root,
		Stdout:   &stdout,
		Timings:  true,
	})
	if err != nil {
		t.Fatalf("Validate returned error: %v", err)
	}

	output := stdout.String()
	for _, needle := range []string{
		"timings:",
		"  load_site_config: ",
		"  validate_layout: ",
		"  load_posts: ",
		"  load_pages: ",
		"  validate_content: ",
		"  total: ",
	} {
		if !strings.Contains(output, needle) {
			t.Fatalf("validate output missing %q in %q", needle, output)
		}
	}
}

func TestBuildKeepsInvalidMathForClientRender(t *testing.T) {
	root := testutil.CopyFixture(t, "site-invalid-math")

	err := app.Build(app.BuildOptions{
		SiteRoot: root,
		Clean:    true,
	})
	if err != nil {
		t.Fatalf("Build returned error: %v", err)
	}

	postHTML := testutil.ReadFile(t, filepath.Join(root, "public", "posts", "bad-math", "index.html"))
	if !strings.Contains(postHTML, `\badcommand{x}`) || !strings.Contains(postHTML, `class="sbl-math-inline"`) {
		t.Fatalf("post page missing client-rendered math placeholder: %s", postHTML)
	}
}

func TestBuildKeepsInvalidMermaidForClientRender(t *testing.T) {
	root := testutil.CopyFixture(t, "site-invalid-mermaid")

	err := app.Build(app.BuildOptions{
		SiteRoot: root,
		Clean:    true,
	})
	if err != nil {
		t.Fatalf("Build returned error: %v", err)
	}

	postHTML := testutil.ReadFile(t, filepath.Join(root, "public", "posts", "bad-diagram", "index.html"))
	if !strings.Contains(postHTML, `class="sbl-mermaid"`) || !strings.Contains(postHTML, `A[Start`) {
		t.Fatalf("post page missing client-rendered Mermaid placeholder: %s", postHTML)
	}
}
