package app_test

import (
	"bytes"
	"context"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"sbl/internal/app"
	"sbl/internal/testutil"
)

func TestLiveBuildsAndRebuildsOnContentChange(t *testing.T) {
	root := testutil.CopyFixture(t, "site-basic")
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	errCh := make(chan error, 1)
	go func() {
		errCh <- app.Live(app.LiveOptions{
			SiteRoot:     root,
			Context:      ctx,
			Stdout:       io.Discard,
			Stderr:       io.Discard,
			PollInterval: 20 * time.Millisecond,
			Debounce:     20 * time.Millisecond,
		})
	}()

	postOutput := filepath.Join(root, "public", "posts", "hello-world", "index.html")
	waitForFileContains(t, postOutput, "Hello World")

	sourcePath := filepath.Join(root, "content", "posts", "hello-world", "index.md")
	updated := strings.ReplaceAll(
		testutil.ReadFile(t, sourcePath),
		"This is the first post generated by `sbl`.",
		"This is the rebuilt post generated by `sbl live`.",
	)
	if err := os.WriteFile(sourcePath, []byte(updated), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	waitForFileContains(t, postOutput, "This is the rebuilt post generated by <code>sbl live</code>.")

	cancel()
	waitForLiveStop(t, errCh)
}

func TestLiveRecoversAfterBuildFailure(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "content", "posts", "hello-world"), 0o755); err != nil {
		t.Fatalf("MkdirAll returned error: %v", err)
	}
	postSource := "---\n" +
		"title: \"Hello World\"\n" +
		"date: 2026-04-12\n" +
		"summary: \"My first post.\"\n" +
		"---\n\n" +
		"## Welcome\n\n" +
		"This site was built with `sbl`.\n"
	if err := os.WriteFile(filepath.Join(root, "content", "posts", "hello-world", "index.md"), []byte(postSource), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	errCh := make(chan error, 1)
	go func() {
		errCh <- app.Live(app.LiveOptions{
			SiteRoot:     root,
			Context:      ctx,
			Stdout:       io.Discard,
			Stderr:       io.Discard,
			PollInterval: 20 * time.Millisecond,
			Debounce:     20 * time.Millisecond,
		})
	}()

	configDir := filepath.Join(root, "config")
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		t.Fatalf("MkdirAll returned error: %v", err)
	}
	configData := "title: Fixture Blog\nbase_url: https://example.test\n"
	if err := os.WriteFile(filepath.Join(configDir, "site.yaml"), []byte(configData), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	waitForFileContains(t, filepath.Join(root, "public", "index.html"), "Fixture Blog")

	cancel()
	waitForLiveStop(t, errCh)
}

func TestLivePrintsTimingsOnShutdown(t *testing.T) {
	root := testutil.CopyFixture(t, "site-basic")
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	var stdout bytes.Buffer
	errCh := make(chan error, 1)
	go func() {
		errCh <- app.Live(app.LiveOptions{
			SiteRoot:     root,
			Context:      ctx,
			Stdout:       &stdout,
			Stderr:       io.Discard,
			PollInterval: 20 * time.Millisecond,
			Debounce:     20 * time.Millisecond,
			Timings:      true,
		})
	}()

	waitForFileContains(t, filepath.Join(root, "public", "index.html"), "Fixture Blog")

	cancel()
	waitForLiveStop(t, errCh)

	output := stdout.String()
	for _, needle := range []string{
		"watching ",
		"built 1 posts and 1 pages",
		"timings:",
		"  initial_scan: ",
		"  initial_build.load_site_config: ",
		"  initial_build.render_posts: ",
		"  initial_build.total: ",
		"  total: ",
	} {
		if !strings.Contains(output, needle) {
			t.Fatalf("live output missing %q in %q", needle, output)
		}
	}
}

func waitForFileContains(t *testing.T, path, needle string) {
	t.Helper()

	deadline := time.Now().Add(3 * time.Second)
	for time.Now().Before(deadline) {
		data, err := os.ReadFile(path)
		if err == nil && strings.Contains(string(data), needle) {
			return
		}
		time.Sleep(20 * time.Millisecond)
	}

	data, _ := os.ReadFile(path)
	t.Fatalf("timed out waiting for %s to contain %q, got %q", path, needle, string(data))
}

func waitForLiveStop(t *testing.T, errCh <-chan error) {
	t.Helper()

	select {
	case err := <-errCh:
		if err != nil {
			t.Fatalf("Live returned error: %v", err)
		}
	case <-time.After(2 * time.Second):
		t.Fatal("timed out waiting for live mode to stop")
	}
}
